### ISSUE TITLE
POLIQARP - Parsing Error in RegEx

### ISSUE THREAD

**Issue by notesjor** [KorAP/Koral#146]
If you use the escape char '\' in a polqarp-Regex, you recived an error.

Query: 

like: "*\\*innen$"

HTTP-Request:

https://korap.ids-mannheim.de/api/v1.0/search?context=sentence&cutoff=false&ql=poliqarp&q=%22%2A%5C%2Ainnen%24%22&page=1

Result:

`
{
    "meta": {
        "startPage": 1,
        "snippets": true,
        "context": "sentence",
        "tokens": false,
        "cutOff": false,
        "timeout": 90000
    },
    "@context": "http://korap.ids-mannheim.de/ns/koral/0.3/context.jsonld",
    "errors": [
        [
            302,
            "Failing to parse at symbol: '\\'",
            2
        ],
        [
            302,
            "Could not parse query >>> \"*\\*innen$\" <<<."
        ]
    ]
}
`

**Comment by notesjor** [comment]
What would be the alternative? - The search should be for all tokens ending with \*innen, e.g. Ärzte*innen (doctors). It seems that the problem exists because the \* is not escaped properly.

**Comment by Akron** [comment]
The alternative is, as described, `".*\*innen$"`. It does, what you want - but the data is on purpose not tokenized that way in DeReKo. If I parse your question wrong, it may be because GitHub put away some characters.
