### ISSUE TITLE
Move foundry/layer/key in spans to term

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#2]
*This is moved from the old Trac Ticket #202*

**jbingel** reported:

 Currently, the foundry, layer and key constraints in spans are serialised differently than in tokens. For spans, &lt;mate/c=np&gt; is serialised as
```json
{
  "@type":"korap:span",
  "foundry":"mate",
  "layer":"c",
  "key":"np"
}
```

whereas for tokens, [mate/p=N] is wrapped in a term:

```json
{
  "@type":"korap:token",
  "wrap": {
    "@type":"korap:term",
    "foundry":"mate",
    "layer":"p",
    "key":"N"
  }
}
```

There is a reason for this, namely that the constraints in tokens can be combined by ANDs and ORs using a korap:termGroup. That's not possible (yet?) for spans.

A reason against this approach is to minimise the specifications. A korap:span would then have a significantly lower number of attributes, as they're outsourced to korap:term, which can hold the attributes foundry/layer/key already. So the span serialisation would be like this:

```json
{
  "@type":"korap:span",
  "wrap": {
    "@type":"korap:term",
    "foundry":"mate",
    "layer":"c",
    "key":"np"
  }
}
```

Any more pros/cons before we decide whether to put this into effect?

Maybe we should really support the sort of logical connection for span key that we already have for tokens, i.e. allow something like

```xml
<cnx/c=vp | cnx/c=advp>
```

Then we'd definitely need a similar mechanism as in tokens, naturally using term/termGroup in a "wrap" attribute, liko so:

```json
{
  "@type":"korap:span",
  "wrap": {
    "@type":"korap:termGroup",
    "operation":"operation:or",
    "operands":[ {
      "@type":"korap:term",
      "foundry":"cnx",
      "layer":"c",
      "key":"vp"
    }, {
      "@type":"korap:term",
      "foundry":"cnx",
      "layer":"c",
      "key":"advp"
    } ]
}
```

Possibly problematic: syntactic ambiguity between attributes (root=true) and layer/key definitions (c=NP).

**Akron** replied:
But effectively this is identical to &lt;cnx/c=vp&gt;|&lt;cnx/c=advp&gt;, right? So I don't see at least any benefit for Poliqarp+. Regarding spans this might work - although deserialization becomes a bit more complicated (especially with negative matches).

**Comment by jbingel** [comment]
True, `<cnx/c=vp>|<cnx/c=advp>` is equivalent to `<cnx/c=vp | cnx/c=advp>`, but for conjunctions there is no such equivalence, cf. `<cnx/c=vp & mate/c=advp>`.

**Comment by Akron** [comment]
```matches(<cnx/c=vp>, <mate/c=advp>)``` is equivalent to ```<cnx/c=vp & mate/c=advp>```, right?

**Comment by jbingel** [comment]
Sure, but it's certainly less intuitive and user-friendly than the `&` option, as the presence of that option in tokens may suggest to users that it is available for spans, too. But yes, we could go with `matches()` only.

**Comment by Akron** [comment]
As I said - I see a problem with negation here, and the positional queries may work clear in that way. In addition: How would this look like with attributes?

**Comment by jbingel** [comment]
It could be `<cnx/c=vp & mate/c=advp arity=3>` -- admittedly, this is quite ugly. However, the combination of terms and attributes is a design problem of PoliqarpPlus and should not limit the possibilities for KoralQuery. Of course, this argument also weakens my former comment on intuitive QL design. But PoliqarpPlus may simply not support this feature, while KoralQuery still offers it.

As for negation, I'm too far away from the deserialisation module to be able to assess the complications that come with termGroups here. If it's too problematic, let's ditch this.

**Comment by Akron** [comment]
And it looks eben more ugly with attribute groups. As far as I can see, there is no design problem yet, so we shouldn't introduce it.
I am not questioning the usefulness of this KoralQuery extension - only the usefulness of the extension in Poliqarp+.

The problem is not deserialization specific. If you have ```<cnx/c=vp & cnx/c!=np>```, does it mean, a cnx/c=np is not allowed anywhere there, or is it just not allowed, in case it has the same start and end positions? For tokens the interpretation is clear - for spans not so.

**Comment by Akron** [comment]
Spans seem to be already serialized that way and Krill supports it (at least for terms - not for termgroups). I will therefore close the issue.
