### ISSUE TITLE
Failed test in the CollectionQueryDuplicateTest in the master-branch

### ISSUE THREAD

**Issue by margaretha** [KorAP/Koral#24]
Failed tests:   testCollectionQueryDuplicateThrowsAssertionException(de.ids_mannheim.korap.query.serialize.CollectionQueryDuplicateTest)

**Comment by michaelhanl** [comment]
Fixed in commit " 78208a8". Due to duplicated collection section in serialized query.

**Comment by Akron** [comment]
This was fixed and now seems to be back in master?

**Comment by Akron** [comment]
This issue was also identical to #10 - I close both.
