### ISSUE TITLE
Poliqarp Plus query: empty token with quantifier.

### ISSUE THREAD

**Issue by margaretha** [KorAP/Koral#26]
query: []{3}
should generate a koral group 
{@type:koral:group,
operation:operation:repetition,
operands:[{@type:koral:token}],
boundary:{@type:koral:boundary,min:3,max:3}
}
Currently, it only generates "query":{"@type":"koral:token"}

See de.ids_mannheim.korap.query.serialize.PoliqarpPlusQueryProcessorTest.testEmptyTokens()

**Comment by Akron** [comment]
I can't verify that bug. The test seems to be wrong.
I pushed a reformulation of the test via Gerrit (waiting for review). This test passes.
Will close this ticket, once the reformulation is accepted by you.
