### ISSUE TITLE
Distance with optionality

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#28]
Currently Koral transforms sequences with intermediate any tokens into distances, like ```der [] Mann``` into ```distance(+1, der, Mann)```. This works, and is fine with Krill. Unfortunately Koral does the same for distances with optional anchors, like ```der [] Mann?```. The Problem here is, that with a distance, the meaning is altered. Without a distance, the query means: "Find a sequence of two tokens, with the first being 'der', followed by 'Mann'". With a distance the query means "Find a span with a single token distance between 'der' and 'Mann', where 'Mann' is optional". I think, in case of optionality on one or both sides, the any token shouldn't be rewritten to a distance..

**Comment by Akron** [comment]
@margaretha wrote

> If we would like to keep Koral simple, then it would not need to
> interpret empty token as a distance in a sequence at the first place. I
> think it has already been quite specific. Other search engines than
> Krill might have other stragegies to handle the empty token case.

I agree. We should remove this kind of interpretation from the Poliqarp processor altogether.

**Comment by margaretha** [comment]
I have updated the Antlr parser grammar for Poliqarp in the antlr-grammars branch. Now empty tokens are treated just as normal tokens.

**Comment by Akron** [comment]
Looks good - thank you! Please merge to master!
