### ISSUE TITLE
operation:position and exclude

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#33]
While implementing a draft for the ```exclude``` option in ```operation:position```, I had the assumption that the Koral description 

> If true, negate positional relations.

is not correct. In fact, I would expect, in case someone searches for, e.g., ```containsNot(<dereko/s=s>, [orth=Baum])```, it is not only a flip of the frames, meaning it should find a ```<dereko/s=s>``` that contains something that is not ```[orth=Baum]```, but it should find ```<dereko/s=s>```, that does not contain ```[orth=Baum]```.

In case we agree on that interpretation, I would say, this should be a different operation ```operation:exclusion```, also with frames, but with the result being the span of the first operand only.

**Comment by margaretha** [comment]
sorry I am confused. Do you mean it should not find 
> ```<dereko/s=s>``` that contains something that is not ```[orth=Baum]```

?

I think the results of 
```<dereko/s=s>``` that contains something that is not ```[orth=Baum]```
```<dereko/s=s>``` that does not contain ```[orth=Baum]```
are the same. Can you give a counter example?

Or do you mean that ```<dereko/s=s>``` would also meet the second interpretation?

**Comment by Akron** [comment]
Let's say we have ```<s>Der alte Mann</s><s>Der junge Mann</s>```.
If we now search for ```containsNot(<s>, [orth=alte])```, I think the expected result should be the second sentence only.
There are two alternative readings, I don't like:
1) If we just flip the frames of the position query, we would have a match for the first sentence and a match for the second sentence starting with "alte".
2) If we interpret this like being ```contains(<s>, [orth!=alte])``` we would have five matches, with the first sentence containing "Der" and "Mann" (both tokens that are not "alte"), and three matches for the second sentence.

**Comment by margaretha** [comment]
I like number 1.

ic so number 2 is incorrect since it basically always matches anything as long as a sentence contains something else other than baum.

> 3) If we interpret this like being `contains(<s>, [orth!=alte])` we would have five matches 

wow this is more like matching tokens than sentences. I would think the sentence that has already been a match is not counted/matched anymore.

**Comment by Akron** [comment]
Yes, I also think 1) is correct. But then we only retrieve the first span, so it's basically a different query than ```operation:position```.

> wow this is more like matching tokens than sentences. I would think the sentence that has already been a match is not counted/matched anymore. 

No, that wouldn't work, if you, for example, use classes or focus on something etc.
To only retrieve a single match a ```unique``` query would be necessary.

**Comment by margaretha** [comment]
okay, I agree with adding ```operation:exclusion```.

**Comment by Akron** [comment]
Great! Can you prepare this for Koral code? I will introduce this to KoralQuery.

**Comment by margaretha** [comment]
you mean implementing the serialization?

**Comment by Akron** [comment]
Yes, that would be nice!

**Comment by margaretha** [comment]
okay, i'll look into it

**Comment by Akron** [comment]
Thank you!

**Comment by Akron** [comment]
Or - if our interpretation is wrong for the specific serialization code, document this here, so we can discuss further.

**Comment by margaretha** [comment]
is containsNot() a valid function in Poliqarp+? I cannot find an example for that in the test suite.

**Comment by Akron** [comment]
Oh - there is no example for ```exclude``` - not even in Cosmas2? That's weird ...
I was expecting that ```containsNot()``` is valid. If it's not, please introduce it.

**Comment by margaretha** [comment]
ok, there is no containsNot in poliqarp currently.

Thanks for the hint. I found some exclude examples in cosmas2.

**Comment by Akron** [comment]
Can you validate our interpretation in C2?

**Comment by margaretha** [comment]
The operator ```#IN(%)``` is similar to ```containsNot```, but the results are the other way around.

From C2 web documentation:

> Mit der ausschliessenden Option % von IN läßt sich ein Suchbegriff in einem unerwünschten Kontext ausschliessen.
```IN(LEM('Würde'),'%',ELEM(HEAD))```
Mit ELEM(HEAD) sind jegliche Arten von Überschriften in den IDS-Korpora gekennzeichnet. Damit lassen sich die Treffer von Würde in den Überschriften ausschliessen.

In this case, our interpretation is correct, but the results should be a list of Würde that are not in Head elements. Would this be fine by adding a focus/class to Würde?

In fact, exclusion has not been supported yet. I got this errors when running it in Kalamar:
760, "Exclusion is currently not supported in position operations"
764, "Class reference checks are currently not supported - results may not be correct"

What is class reference check?



```IN(LEM('Würde'),'% L',ELEM(HEAD))``` or ```Würde #IN(% L) <head>```

means Head should not start with Würde according to the position frame doc. Actually L means Linkes Wort von X und Y stimmen überein (from C2 doc). I don't really get what it means with "the left word of" from this description.

**Comment by margaretha** [comment]
Actually ```#IN(%)``` is *not* similar to ```containsNot```.

According to the position frame doc,
```contains()``` would be comparable to ```#IN(N)``` that is using frame:isAround

so should ```containsNot()``` be```#IN(% N)```? 

I dont really understand why```#IN(%)``` uses all the following frames: succeeds, succeedsDirectly, overlapsRight, alignsRight, isWithin, alignsLeft, overlapsLeft, precedes, precedesDirectly.

**Comment by margaretha** [comment]
> I dont really understand why```#IN(%)``` uses the following frames: alignsRight, isWithin, alignsLeft (defined in the position frame doc).

It seems that ```X #IN(% N) Y``` means X is the <b> element and Y is the <a> element in the doc.

**Comment by Akron** [comment]
Hi Eliza,
it's a bit hard to answer all these questions in order ... I'll give it a try.

I think ```IN(LEM('Würde'),'%',ELEM(HEAD))``` would need be a direct translation of our serialization with ```operation:exclusion```, so the first span is the result only. The frames would be ```["frames:isWithin", "frames:alignsRight", "frames:matches", "frames:alignsLeft"]```.

> In this case, our interpretation is correct, but the results should be a list of Würde that are not in Head elements. Would this be fine by adding a focus/class to Würde?

That's not needed.

> In fact, exclusion has not been supported yet. I got this errors when running it in Kalamar.

Sure. We are just deciding how the behaviour should be. ;)

> What is class reference check?

The class reference check will test if classes are equal, differ, intersect, include etc.

> means Head should not start with Würde according to the position frame doc. Actually L means Linkes Wort von X und Y stimmen überein (from C2 doc). I don't really get what it means with "the left word of" from this description.

Me neither. ;)

> > According to the position frame doc, contains() would be comparable to #IN(N) that is serialized using frame:isAround

> Thats's weird. startswith and endswith should also be okay.

No - the [Cosmas2 reference](http://www.ids-mannheim.de/cosmas2/web-app/hilfe/suchanfrage/eingabe-zeile/thematische-bsp/bsp-satzposition.html) says "weder am Satzanfang noch -ende".

**Comment by margaretha** [comment]
Hi Nils, thanks. the order does not matter :)

> I think ```IN(LEM('Würde'),'%',ELEM(HEAD))``` would need be a direct translation of our serialization with ```operation:exclusion```, so the first span is the result only. The frames would be ```["frames:isWithin", "frames:alignsRight", "frames:matches", "frames:alignsLeft"]```.

I don't get this. I assume ```operation:exclusion``` would have two operands, let say the first operand is "what to exclude" and the second  operand is "where from". The frames also assume such operand structure, right? Although ```contains()``` would order it the other way around...
So how would we know which operand should be returned?

> Sure. We are just deciding how the behaviour should be. ;)

Oh I thought it has been implemented :)

> No - the [Cosmas2 reference](http://www.ids-mannheim.de/cosmas2/web-app/hilfe/suchanfrage/eingabe-zeile/thematische-bsp/bsp-satzposition.html) says "weder am Satzanfang noch -ende".

Yes, the frame is correct for ```#IN(N)```, but does ```contains()``` in poliqarp also not include startswith and endswith?

**Comment by Akron** [comment]
> I don't get this. I assume operation:exclusion would have two operands, let say the first operand is "what to exclude" and the second operand is "where from".

As I said in the initial post, I would see this the other way around:

> ... I would say, this should be a different operation operation:exclusion, also with frames, but with the result being the span of the first operand only.

> So how would we know which operand should be returned?

Always the first.

> Oh I thought it has been implemented :)

I had it with an inversion of the frames - before I learned that this is actually wrong.

> Yes, the frame is correct for #IN(N), but does contains() in poliqarp also not include startswith and endswith?

No. Where does it says that contains() is equal to #IN(N)?

**Comment by margaretha** [comment]
> ... I would say, this should be a different operation operation:exclusion, also with frames, but with the result being the span of the first operand only.

But this makes the frame type reading unnatural, e.g. first operand (where from) isWithin second operand (what to exclude)

> No. Where does it says that contains() is equal to #IN(N)?
because the serialization of contains() only has frames:isAround.

**Comment by Akron** [comment]
>> ... I would say, this should be a different operation operation:exclusion, also with frames, but with the result being the span of the first operand only.

> But this makes the frame type reading unnatural, e.g. first operand (where from) isWithin second operand (what to exclude)

I would read it as "X that is not Within Y" ... ?

> because the serialization of contains() only has frames:isAround.

That sounds wrong though.

**Comment by margaretha** [comment]
> I would read it as "X that is not Within Y" ... ?

oh sorry, I mixed this up. I was thinking about contains. For C2 IN operation, X is the first operand and Y is the second. It's fine. On the otherhand, poliqarp containsNot(Y,X), Y is  the first operand and X is the second. so the frame would be read Y is not within X, or how would we know which is within what?

> That sounds wrong though.

Yup.

**Comment by Akron** [comment]
> Y is the first operand and X is the second. so the frame would be read Y is not within X, or how would we know which is within what?

The serialization of operands should acknowledge that, yes.

**Comment by margaretha** [comment]
huh, what do you mean?

**Comment by Akron** [comment]
That the serialization of Poliqarp's ```containsNot()``` should revert the operand order.

**Comment by margaretha** [comment]
oh okay.

btw, I found ```frames:contains``` in C2 serializer for N, is this the same as ```frames:isAround```?

**Comment by Akron** [comment]
> > That the serialization of Poliqarp's containsNot() should revert the operand order.
> ok it's not a problem, but how would Krill knows how to solve it?

What do you mean? There shouldn't be an ambiguity.

> btw, I found ```frames:contains``` in C2 serializer for N, is this the same as ```frames:isAround```?

Oh - that's an unknown frame. I don't know what its purpose ist.

**Comment by margaretha** [comment]
> What do you mean? There shouldn't be an ambiguity.
 
For example, for ```containsNot(Y,X)``` the operands are [Y,X] since Y should be returned (the output),
while for ```X #IN(N) Y```, the operands are [X,Y], since X should be returned,
with ["frames:isWithin", "frames:alignsRight", "frames:matches", "frames:alignsLeft"]

Both queries should be handled the same way in Krill, but how would it knows which is within which, since the order of the operands differ? If it just takes the operands as they are, would not there be 2 different queries for frames:isWithin, namely isWithin(Y,X) and isWithin(X,Y) ?

> Oh - that's an unknown frame. I don't know what its purpose ist.

hm, maybe it was an old frame / deprecated code. It seems like it's not used since the output does not contain frames:contains.

**Comment by margaretha** [comment]
>> Oh - that's an unknown frame. I don't know what its purpose ist.

> hm, maybe it was an old frame / deprecated code. It seems like it's not used since the output does not contain frames:contains.

sorry it is actually used, and wrong then. I'll change it frames:isAround

**Comment by Akron** [comment]
> Is classRefCheck documented somewhere? I would like to make the options as enums.

It's documented in the Position Frames GoogleDoc.

**Comment by margaretha** [comment]
> It's documented in the Position Frames GoogleDoc.

thanks. there is "differs" in the doc, and "unequals" code. which one is correct?

**Comment by Akron** [comment]
> For example, for ```containsNot(Y,X)``` the operands are ```[Y,X]``` since ```Y``` should be returned (the output) with ```["frames:isWithin", "frames:alignsRight", "frames:matches", "frames:alignsLeft"]```-
While for ```X #IN(% N) Y```, the operands are ```[X,Y]```, since ```X``` should be returned,
with ```["frames:isWithin"]```.

The order in the QL is irrelevant, as long as the order in KQ is correct. So the serialization should always have the resulting query as its first argument.

> thanks. there is "differs" in the doc, and "unequals" in the code. which one is correct?

I have no idea. Which is used in the serialization?

**Comment by margaretha** [comment]
```wegen #IN(N) <s>``` is now serialized as

<pre>
"query": {
        "@type": "koral:reference",
        "operation": "operation:focus",
        "classRef": [130],
        "operands": [{
            "@type": "koral:group",
            "operation": "operation:position",
            "operands": [
                {
                    "@type": "koral:group",
                    "operation": "operation:class",
                    "classOut": 129,
                    "operands": [{
                        "@type": "koral:span",
                        "wrap": {
                            "@type": "koral:term",
                            "key": "s"
                        }
                    }]
                },
                {
                    "@type": "koral:group",
                    "operation": "operation:class",
                    "classOut": 130,
                    "operands": [{
                        "@type": "koral:token",
                        "wrap": {
                            "@type": "koral:term",
                            "key": "wegen",
                            "layer": "orth",
                            "match": "match:eq"
                        }
                    }]
                }
            ],
            "frames": ["frames:isAround"],
            "frame": null
        }]
    }
</pre>

I think i can remove  "frame": null since there is no frame attribute in the specification.

I would serialize ```wegen #IN(% N) <s>``` as:

<pre>
query": {
    "@type": "koral:group",
    "operation": "operation:exclusion",
    "operands": [
        {
            "@type": "koral:token",
            "wrap": {
                "@type": "koral:term",
                "key": "wegen",
                "layer": "orth",
                "match": "match:eq"
            }
        },
        {
            "@type": "koral:span",
            "wrap": {
                "@type": "koral:term",
                "key": "s"
            }
        }
    ],
    "frames": ["frames:isWithin"]
}
</pre>

Is it okay?

Another case: the serialization of ```wegen #IN(L) <s>``` is similar to ```wegen #IN(N) <s>```, except the frames are  ["frames:startsWith", "frames:matches"], so for ```wegen #IN(% L) <s>```, I would set the frames ["frames:alignLeft", "frames:matches"].

**Comment by margaretha** [comment]
>> thanks. there is "differs" in the doc, and "unequals" in the code. which one is correct?

>I have no idea. Which is used in the serialization?

Unequals. let's stick with it.

**Comment by Akron** [comment]
The serialization of ```wegen #IN(% N) <s>``` looks correct. So matches would occur with ```wegen``` outside or at the beginning or at the end of sentences (principally also overlappingly, but as it is one word, that can't occur here).

If I understand the query correctly, for ```wegen #IN(% N) <s>``` the frames need to be exactly the same like with ```wegen #IN(N) <s>``` - so the frames are really just depending on the operand order. In case you switch operand orders, you need to change cases. But why did you switch the operands for the first serialization?

**Comment by margaretha** [comment]
> But why did you switch the operands for the first serialization?

It was implemented that way. I also think it is weird so I changed it like this:

<pre>
{
    "@context": "http://korap.ids-mannheim.de/ns/koral/0.3/context.jsonld",
    "query": {
        "operation": "operation:focus",
        "operands": [{
            "operation": "operation:position",
            "frames": ["frames:isWithin"],
            "operands": [
                {
                    "operation": "operation:class",
                    "operands": [{
                        "wrap": {
                            "@type": "koral:term",
                            "layer": "orth",
                            "match": "match:eq",
                            "key": "wegen"
                        },
                        "@type": "koral:token"
                    }],
                    "@type": "koral:group",
                    "classOut": 129
                },
                {
                    "operation": "operation:class",
                    "operands": [{
                        "wrap": {
                            "@type": "koral:term",
                            "key": "s"
                        },
                        "@type": "koral:span"
                    }],
                    "@type": "koral:group",
                    "classOut": 130
                }
            ],
            "@type": "koral:group"
        }],
        "@type": "koral:reference",
        "classRef": [130]
    }
}
</pre>

The focus is needed because #IN without exclusion should return the total/combination span of both operands. So I take the second span.

**Comment by Akron** [comment]
> The focus is needed because #IN without exclusion should return the total/combination span of both operands. So I take the second span.

But the total span of both operands in an ```operation:position``` is the default output of the query. Why is the focus necessary?

**Comment by margaretha** [comment]
> But the total span of both operands in an operation:position is the default output of the query. Why is the focus necessary?

Is it not the first operand? Then I got it wrong and all OP IN with exclusion needs a focus on the first operand.

**Comment by Akron** [comment]
There are 2 different operations now: ```operation:position``` and ```operation:exclusion```. To cite the first post:

>  I would say, this should be a different operation ```operation:exclusion```, also with frames, but with the result being the span of the first operand only.

That means, ```operation:position``` always returns the joined span of both operands, while ```operation:exclusion``` only returns the span of the first operand (because the second is not allowed to be part of the result per definition). In your last example you are refering to ```operation:position```, where a focus is not needed, when you are refering to the joined span of both operands. In ```operation:exclusion``` a focus on the first operand would be equivalent to no focus at all, and a focus on the second operand would either be ignored or should throw an error, because you can't focus on anything that's not in part of the result per definition.

**Comment by margaretha** [comment]
> operation:exclusion only returns the span of the first operand (because the second is not allowed to be part of the result per definition)

It is a bit strange because all other operation always returns joined spans. well, but we can define it in the KQ doc.

**Comment by Akron** [comment]
```operation:disjunction``` also returns the span of one operand only.

I can add this to the KQ doc now.

**Comment by margaretha** [comment]
ok thanks.

**Comment by Akron** [comment]
I think this can be closed now.

**Comment by margaretha** [comment]
well, i am still not sure about operation IN without extra arguments. It is serialized into an operation:position without any frame and wrapped with a classRefCheck. Actually classRefCheck only would be sufficient but operation:class does not allow multiple operands.

<pre>
    "query": {
        "classRefCheck": ["classRefCheck:includes"],
        "operation": "operation:class",
        "operands": [{
            "operation": "operation:position",
            "frames": [],
            "operands": [
                {
                    "operation": "operation:class",
                    "operands": [{
                        "wrap": {
                            "@type": "koral:term",
                            "layer": "orth",
                            "match": "match:eq",
                            "key": "wegen"
                        },
                        "@type": "koral:token"
                    }],
                    "@type": "koral:group",
                    "classOut": 130
                },
                {
                    "operation": "operation:class",
                    "operands": [{
                        "wrap": {
                            "@type": "koral:term",
                            "key": "s"
                        },
                        "@type": "koral:span"
                    }],
                    "@type": "koral:group",
                    "classOut": 129
                }
            ],
            "@type": "koral:group"
        }],
        "@type": "koral:group",
        "classOut": 131,
        "classIn": [
            129,
            130
        ]
    }
</pre>

**Comment by Akron** [comment]
I think it's better to open a new issue.

**Comment by margaretha** [comment]
ok
