### ISSUE TITLE
Replace LinkedHashMap

### ISSUE THREAD

**Issue by margaretha** [KorAP/Koral#35]
I don't see why requestMap and queryMap (such as in the C2 serialization) should be LinkHashMaps. Does the order of the attributes in KoralQuery important?

**Comment by Akron** [comment]
I don't know. There is no specific order of attributes. Maybe @jbingel used it to make testing of serialization simpler before he switched to JSON-Pointers?
If the tests are fine after switching - feel free to switch. Although I don't know if there are real benefits.

**Comment by margaretha** [comment]
Ok. I haved replaced it and it seems to work fine.
