### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#41]
The command line implementation seems to be disabled at the moment.
The command

```java -jar target/Koral-0.25.jar "der alte" "Poliqarp"```

results in nothing.

**Comment by margaretha** [comment]
I've just tested it using a fresh copy from the repo. It works fine. 
Did you "mvn install" it?

**Comment by Akron** [comment]
No, I ```mvn package```d it.

**Comment by margaretha** [comment]
The maven dependency plugin was set to the install phase . I've changed it package now.

**Comment by Akron** [comment]
Thank you!

**Comment by Akron** [comment]
It still seems not to work though.

**Comment by margaretha** [comment]
Mine works just fine. I even tried using a fresh copy from the repo.

**Comment by Akron** [comment]
Hm ... do you use the exact same command?

**Comment by margaretha** [comment]
yes, just mvn package

**Comment by Akron** [comment]
And then ```java -jar target/Koral-0.26.jar "der alte" "Poliqarp"```? This still gives me no results.

**Comment by margaretha** [comment]
It seems that the printing was set with log4j. I have just changed it. Could you try again with a new copy from the repo?

**Comment by Akron** [comment]
Ah - thank you! Yes - that works now. And I think it's better to not use log4j for non-logging output.
Is the "Serialized query: " prefix necessary?

**Comment by margaretha** [comment]
no, I can remove it if it is not desired.

**Comment by Akron** [comment]
I think if this would be used as part of another script, prefixing is not desired.

**Comment by Akron** [comment]
I close this issue as being fixed. Thanks for your work!
