### ISSUE TITLE
Support verbatim string values in Poliqarp

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#42]
Currently strings can not be passed to Koral when they contain special characters.
So ```[orth=http://spiegel.de]``` does not work and ```[orth="http://spiegel.de"]``` only kind of works - as it translates the string to a regular expression. I would propose ```[orth='http://spiegel.de']``` to be a way to pass verbatim string values. Currently this construct translates to regular expressions as well, but I don't think this is necessary.

**Comment by margaretha** [comment]
The fix alters Poliqarp syntax regarding single quotes and thus becomes part of Poliqarp+. Originally Poliqarp treats all expression values as regex only.
