### ISSUE TITLE
C2 OP IN

### ISSUE THREAD

**Issue by margaretha** [KorAP/Koral#43]
```wegen #IN <s>```
is serialized into:
<pre>
{
    "@context": "http://korap.ids-mannheim.de/ns/koral/0.3/context.jsonld",
    "query": {
        "classRefCheck": ["classRefCheck:includes"],
        "operation": "operation:class",
        "operands": [{
            "operation": "operation:position",
            "frames": [],
            "operands": [
                {
                    "operation": "operation:class",
                    "operands": [{
                        "wrap": {
                            "@type": "koral:term",
                            "layer": "orth",
                            "match": "match:eq",
                            "key": "wegen"
                        },
                        "@type": "koral:token"
                    }],
                    "@type": "koral:group",
                    "classOut": 130
                },
                {
                    "operation": "operation:class",
                    "operands": [{
                        "wrap": {
                            "@type": "koral:term",
                            "key": "s"
                        },
                        "@type": "koral:span"
                    }],
                    "@type": "koral:group",
                    "classOut": 129
                }
            ],
            "@type": "koral:group"
        }],
        "@type": "koral:group",
        "classOut": 131,
        "classIn": [
            129,
            130
        ]
    }
}
</pre>

operation:position with empty frames does not really make sense. This should possibly be reduced to operation:class only, but it does not allow multiple operands.

Besides, ```wegen #IN(%) <s>``` should be serialized with ```"classRefCheck": ["classRefCheck:disjoint"]```.

**Comment by Akron** [comment]
The serialization is weird. In my opinion the ```classRefCheck``` does not make any sense here at all.

**Comment by margaretha** [comment]
Maybe classRefCheck was used to simplify the search instead of adding all kinds of frames. 
```wegen #IN <s>``` needs isWithin, alignsLeft, alignsRight, matches.

**Comment by Akron** [comment]
Hm - but that would never simplify the search, because it would mean that the ```operation:position``` has to match all configurations where both operands occur in the same document, before the ```classRefCheck``` filters based on class spans.

**Comment by margaretha** [comment]
yeah thats why I thought operation:position is needed anymore.

**Comment by Akron** [comment]
But isn't it the other way around? classRefCheck is not needed, because the requirement can be formulated as a ```operation:position```?

**Comment by margaretha** [comment]
I think either way is ok. But it is not possible to have multiple operands in operation:class anyway. so let's remove it and use operation:position only.

**Comment by Akron** [comment]
Well - ```classrefCheck``` will always be more complicated as a serialization here, as it requires classes set, while ```operation:position``` refers to the simple operand's spans.

**Comment by margaretha** [comment]
actually, classrefCheck was added everywhere for other frames as well, but I think it is not necessary and operation:position only is enough.

**Comment by Akron** [comment]
I remember that there were a lot of situations in COSMAS II where it was indeed necessary. But in this example I can't think of a good reason.

**Comment by margaretha** [comment]
ok, i have changed the serialization as follows:

<pre>
"query": {
        "operation": "operation:position",
        "frames": [
            "frames:alignsLeft",
            "frames:alignsRight",
            "frames:isWithin",
            "frames:matches"
        ],
        "operands": [
            {
                "wrap": {
                    "@type": "koral:term",
                    "layer": "orth",
                    "match": "match:eq",
                    "key": "wegen"
                },
                "@type": "koral:token"
            },
            {
                "wrap": {
                    "@type": "koral:term",
                    "key": "s"
                },
                "@type": "koral:span"
            }
        ],
        "@type": "koral:group"
    }
</pre>

It is identical with exclusion, except the operation is operation:exclusion.

**Comment by Akron** [comment]
Looks good to me.

**Comment by margaretha** [comment]
Since KorAP always returns joined spans where there are more than one hit like in distance queries, the arguments ALL and HIT would not matter / have the same serialization/results, wouldn't they?

C2 query example:
```sich #IN(N,HIT) (&gelten /w5:10 zurecht)```
returns no result because ```sich``` is only searched in the occurrences of ```&gelten``` and ```zurecht```.

```sich #IN(N,ALL) (&gelten /w5:10 zurecht)```
returns some results because ```sich``` is searched in the joined span of between ```&gelten``` and ```zurecht``` like KorAP distance spans.

Or should we try to support the OP IN HIT like in C2?

**Comment by Akron** [comment]
Can you give me the doc were this operator is described? I can't find it. And yes - we should replicate the COSMAS II behaviour as far as possible.

**Comment by margaretha** [comment]
[This](http://www.ids-mannheim.de/cosmas2/win-app/hilfe/suchanfrage/eingabe-grafisch/syntax/ARGUMENT_I.html) is about HIT etc.

[This](http://www.ids-mannheim.de/cosmas2/win-app/hilfe/suchanfrage/eingabe-grafisch/syntax/IN.html) is about IN.

**Comment by Akron** [comment]
Thank you - now I remember. The serialization was with ```classRefCheck:includes``` to treat it as HIT. However - this is not necessary, if the second operand is not a complex operand. If the second operand is e.g. another positional group, introducing ```classRefCheckOp``` makes sense.

Regarding ```X #IN(%,HIT) Y``` it's a bit more complicated I think. This would probably be something like ```(notWithin(X,Y)|classRefCheck(disjoints:within(X,Y)))``` ...

**Comment by margaretha** [comment]
> The serialization was with classRefCheck:includes to treat it as HIT. 

I don't get how classRefCheck:includes can solve HIT.

> However - this is not necessary, if the second operand is not a complex operand.

How can I identify if the second operand is complex or not?

> If the second operand is e.g. another positional group, introducing classRefCheckOp makes sense.

Which classRefCheckOp? Why?

**Comment by Akron** [comment]
>> The serialization was with classRefCheck:includes to treat it as HIT.

> I don't get how classRefCheck:includes can solve HIT.

Your example ```sich #IN(N,HIT) (&gelten /w5:10 zurecht)``` has a complex query as Y, and HIT would refer only to the classes set for ```&gelten``` and ```zurecht```. That makes a classRefCheck necessary to filter on all positional matches of X and Y. 

>> However - this is not necessary, if the second operand is not a complex operand.

> How can I identify if the second operand is complex or not?

That's a good question and I can't give you a simple answer to that.

>> If the second operand is e.g. another positional group, introducing classRefCheckOp makes sense.

> Which classRefCheckOp? Why?

```classRefCheck:includes```, because this checks for the HIT constraint.
I suppose that was the reason, ```classRefCheck``` was introduced for every non-ALL queries from COSMAS II. Removing unnecessary ```classRefCheck```s can very well be done at a later point, but it may be beneficial not to serialize them at all. The first example should have positional frames nontheless, although, even that *could* be optimized at a later point for this exact type of query (introducing positional frames based on ```classRefCheck``` constraints for non complex positional operands).

**Comment by margaretha** [comment]
> That makes a classRefCheck necessary to filter on all positional matches of X and Y.

but ```classRefCheck:includes``` just checks if the intersection of both operands equals to the second operand. So it checks if there is an intersection between ```sich``` and ```(&gelten /w5:10 zurecht)```, not among the classes of ```&gelten``` and ```zurecht```.

**Comment by Akron** [comment]
> but ```classRefCheck:includes``` just checks if the intersection of both operands equals to the second operand.

No, it does not check for operands, but for classes. Of course, ```&gelten``` and ```zurecht``` need classes, ```(&gelten /w5:10 zurecht)``` does not.

**Comment by margaretha** [comment]
ic, sry I misunderstood because  ```&gelten``` and ```zurecht``` are not direct operands of operation:position (OP IN). That's why I am also not sure how to put the classes for them.  

classIn should contain all the classes needed to be checked in operand 2 and it does not need a classOut, right?

> I suppose that was the reason, classRefCheck was introduced for every non-ALL queries from COSMAS II. 

yes since it is default, it has to be added often.

**Comment by Akron** [comment]
> classIn should contain all the classes needed to be checked in operand 2 and it does not need a classOut, right?

Right.

**Comment by margaretha** [comment]
May ```&gelten``` and ```zurecht``` have the same class number?

**Comment by Akron** [comment]
> May ```&gelten``` and ```zurecht``` have the same class number?

Yes, that's preferable in this case.

> Wouldn't multiple classRefChecks be problematic?

No, but in your example, they don't make sense, as ```equals``` implicitely ```includes```. I think the FE is meant to be simply more specific than HIT - maybe Franck can say more. I don't know, why you need class 130. At least in the ```classRefCheck``` it's not necessary.

**Comment by margaretha** [comment]
Fixed in 62d4bca704e86dea329358c61a44c2e4f6ea28c9.

**Comment by Akron** [comment]
After rereading and testing with Cosmas II I can give a bit more qualified feedback regarding #IN. In [Cosmas 2](http://www.ids-mannheim.de/cosmas2/win-app/hilfe/suchanfrage/eingabe-zeile/syntax/in.html) it says:

> Obwohl es sich um einen Kombinationsoperator handelt, enthält das Resultat nur die Liste der Suchbegriffe X, die die Suchanfrage erfüllen.

So I expect the first operand to always be classed and to have a focus on that operand. And if I understand the difference between HIT and ALL correctly, we should not consider separated classes in complex operands.

I made some further comments in the code, see https://github.com/KorAP/Koral/commit/a5439f2fe925e7a48148577e4107bec5693ceafb .
