### ISSUE TITLE
Operation: merge (C2 MAX)

### ISSUE THREAD

**Issue by margaretha** [KorAP/Koral#44]
Argument MAX in C2 groups together matches where multiple hits occur within the same span. For instance,
let Y contains X1, X2, X3, then ```X #IN(N,MAX) Y``` returns only 1 match.

Such grouping can be achieved with ```operation:merge``` with only one operand. This operation (in Krill) should check if the span still have the same start and end position and collects the payloads containing classes of the hits (Xs). Or is any of the classRefOp able to do this?

Serialization of ```wegen #IN(N,MAX) <s>``` would be
<pre>
{
    "@context": "http://korap.ids-mannheim.de/ns/koral/0.3/context.jsonld",
    "query": {
        "operation": "operation:merge",
        "operands": [{
            "operation": "operation:position",
            "frames": [
                "frames:isWithin",
                "frames:matches"
            ],
            "operands": [
                {
                    "operation": "operation:class",
                    "@type": "koral:group",
                    "classOut": 1,
                    "operands": [{
                        "wrap": {
                            "@type": "koral:term",
                            "layer": "orth",
                            "match": "match:eq",
                            "key": "wegen"
                        },
                        "@type": "koral:token"
                    }]
                },
                {
                    "wrap": {
                        "@type": "koral:term",
                        "key": "s"
                    },
                    "@type": "koral:span"
                }
            ],
            "@type": "koral:group"
        }],
        "@type": "koral:group"
    }
}
</pre>

**Comment by Akron** [comment]
Please add this to #36.

**Comment by margaretha** [comment]
Merged with #36. Sry didn't see that.
