### ISSUE TITLE
Annis: foundry/layer value with regex

### ISSUE THREAD

**Issue by margaretha** [KorAP/Koral#47]
Regular expression should be possible for foundry/layer value in Annis query, e.g. ```tt/l=/A.*/```, that is similar to poliqarp query ```[tt/p="A.*"]```. Thus, the serialization should also be the same.

<pre>
"query": {
    "@type": "koral:token",
    "wrap": {
      "@type": "koral:term",
      "foundry": "tt",
      "key": "A.*",
      "layer": "p",
      "match": "match:eq",
      "type": "type:regex"
    }
  }
</pre>

**Comment by margaretha** [comment]
There is probably a problem in [the ANTLR lexer code](https://github.com/KorAP/Koral/blob/master/src/main/antlr/annis/AqlLexer.g4) for Annis because of slash character.

**Comment by Akron** [comment]
If this can't be fixed, we may be able to change the regex symbols instead. I think we should keep the slash to separate foundry and layer.

**Comment by margaretha** [comment]
It is Annis syntax though to surround regex with slash.

**Comment by Akron** [comment]
Sure. What I mean: If the Antlr can't be fixed to support the slash separator, we should modify ANNIS syntax in a way it works.

**Comment by margaretha** [comment]
I can modify the regex in lexer to exclude =
would it be okay?

**Comment by margaretha** [comment]
Another alternative is to define foundry including an optional slash in the lexer. This will result in having  such a foundry: ```tt/``` but it is not that tragic, since it can be cleaned up in ANTLR tree parsing stage / serializer, so the end KoralQuery will have ```tt``` as foundry.

**Comment by margaretha** [comment]
Fixed with the 2nd solution.

**Comment by Akron** [comment]
That sounds like a good solution!
