### ISSUE TITLE
Regular expressions in corpus queries

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#48]
When using regular expressions in corpus queries, some characters are failing to parse. I think, this is similar to the behaviour in Poliqarp, where regex-parsing was fixed by reading the characters verbatim instead of parsing.

I added a failing test in https://github.com/KorAP/Koral/commit/9de87c2ae3818dccb98249de0c8439350a386d4f (branch fix-vc-regex).

**Comment by margaretha** [comment]
Hi Nils, I cannot find the branch. Is it in Gerrit?

**Comment by Akron** [comment]
It's on GitHub, sorry: [fix-vc-regex](https://github.com/KorAP/Koral/compare/fix-vc-regex).

**Comment by margaretha** [comment]
I simplified the regex a lot so that everything surrounded with / is considered as regex. The test suite does not complains. Let me know if this is too verbose.

Fixed in https://github.com/KorAP/Koral/commit/de23f88d82b1cce7919a8368ca335153da273400.

**Comment by Akron** [comment]
Thank you!
