### ISSUE TITLE
Introduce value vectors for "koral:doc"

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#53]
Virtual corpora may be represented as long vectors of different text sigils. This is especially true when migrating VCs from COSMAS II or creating balanced VCs programmatically. To avoid the need to create very large or-Groups of ```koral:doc```s, it would be nice to support value vectors, so a list of different values can be assigned to a single key, indicating an or-relation of the constraint.
Example:
```
"collection": {
    "@type": "koral:doc",
    "key": "textSigle",
    "match": "match:eq",
    "value": ["WPD/204/567","WPD/204/567", ...]
}
```

**Comment by margaretha** [comment]
I suggest to generalize VC caching by adding an attribute: 
```"cache" : "true"```
This would allow any VC to be cached, not necessarily those with array values.

Besides, collection "name" or "id" should also be added for cache keys.

**Comment by Akron** [comment]
This issue is not about caching. Are you refering to another issue?

**Comment by margaretha** [comment]
No, but this serialization is the input in Krill to cache a VC.

**Comment by margaretha** [comment]
The serialization also need valtype attribute to indicate the value type:
```"valtype" : "type:string[]"```

**Comment by Akron** [comment]
The input can be any VC. It's not specific to a value vector serialization in KQ.

Per [KoralQuery](http://korap.github.io/Koral/#koral-doc) ```"type":"type:string"``` is the default.

**Comment by margaretha** [comment]
But the type is not string, it is an array of strings. This should be differentiated from a simple string.

**Comment by Akron** [comment]
What is the benefit?

**Comment by margaretha** [comment]
You are right. There isn't much benefit from it. We should not introduce new type for each possible arrays.

**Comment by margaretha** [comment]
Implemented deserialization of this in https://github.com/KorAP/Krill/commit/ecddb0b23d63605160c19b22353545727ec80957.

**Comment by Akron** [comment]
Documented in https://github.com/KorAP/Koral/commit/598542823616be3eab95d579b604933c2ea898fe .
