### ISSUE TITLE
Do not generate empty collection objects

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#6]
Currently Koral will always create KoralQuery objects with ```"collection" : {}```, in case no collection was set. This is not a valid collection object and will make all queries of that type fail.
Another problem are empty warnings, errors and messages. They are not wrong but annoying in case no error, warning or message was set.

**Comment by Akron** [comment]
In addition: Do not create ```"query" : {}```, in case a query wasn't parseble.

**Comment by michaelhanl** [comment]
currently under review in gerrit!

**Comment by Akron** [comment]
Fixed in master.
